LastSessions<|||>1<|||>reniec_asistencia
LastActiveSession<|||>1<|||>reniec_asistencia
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
ColWidths_frmTableEditor.listColumns<|||>1<|||>40,100,152,90,60,65,50,117,130,139,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>605,100,80,120,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>571,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,417
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,316
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,316,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,186
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,256
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
MainWinWidth<|||>3<|||>881
MainWinHeight<|||>3<|||>467
SessionManager_WindowLeft<|||>3<|||>273
SessionManager_WindowTop<|||>3<|||>79
ColWidths_frmRoutineEditor.listParameters<|||>1<|||>50,407,90,70
ColsVisible_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColPositions_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColSort_frmRoutineEditor.listParameters<|||>1<|||>-1,0
sqloutheight<|||>3<|||>101
MainWinMaximized<|||>3<|||>0
querymemoheight<|||>3<|||>403
FontSize<|||>3<|||>10
queryhelperswidth<|||>3<|||>37
dbtreewidth<|||>3<|||>208
SQLFile0<|||>1<|||>C:\Users\smrj1.DESKTOP-Q4QDIE1\Downloads\a.sql
SQLFile1<|||>1<|||>C:\laragon\bin\heidisql\Backups\query-tab-2026-05-18_10-55-05-038.sql
SQLFile2<|||>1<|||>C:\laragon\bin\heidisql\Backups\query-tab-2026-05-21_11-01-47-986.sql
SQLFile3<|||>1<|||>C:\laragon\bin\heidisql\Backups\query-tab-2026-05-12_12-36-44-617.sql
Servers\nexus_stock_db\SessionCreated<|||>1<|||>2026-05-12 12:34:38
Servers\nexus_stock_db\Host<|||>1<|||>127.0.0.1
Servers\nexus_stock_db\WindowsAuth<|||>3<|||>0
Servers\nexus_stock_db\CleartextPluginEnabled<|||>3<|||>0
Servers\nexus_stock_db\User<|||>1<|||>postgres
Servers\nexus_stock_db\Password<|||>1<|||>78777B7C6F7A6D7B8
Servers\nexus_stock_db\LoginPrompt<|||>3<|||>0
Servers\nexus_stock_db\Port<|||>1<|||>5432
Servers\nexus_stock_db\NetType<|||>3<|||>8
Servers\nexus_stock_db\Compressed<|||>3<|||>0
Servers\nexus_stock_db\LocalTimeZone<|||>3<|||>0
Servers\nexus_stock_db\QueryTimeout<|||>3<|||>30
Servers\nexus_stock_db\KeepAlive<|||>3<|||>20
Servers\nexus_stock_db\FullTableStatus<|||>3<|||>1
Servers\nexus_stock_db\Databases<|||>1<|||>nexus_stock_db
Servers\nexus_stock_db\Library<|||>1<|||>libpq-15.dll
Servers\nexus_stock_db\Comment<|||>1<|||>
Servers\nexus_stock_db\StartupScriptFilename<|||>1<|||>
Servers\nexus_stock_db\TreeBackground<|||>3<|||>536870911
Servers\nexus_stock_db\SSHtunnelActive<|||>3<|||>0
Servers\nexus_stock_db\SshExecutable<|||>1<|||>plink.exe
Servers\nexus_stock_db\SSHtunnelHost<|||>1<|||>
Servers\nexus_stock_db\SSHtunnelHostPort<|||>3<|||>22
Servers\nexus_stock_db\SSHtunnelUser<|||>1<|||>
Servers\nexus_stock_db\SSHtunnelPassword<|||>1<|||>5
Servers\nexus_stock_db\SSHtunnelTimeout<|||>3<|||>4
Servers\nexus_stock_db\SSHtunnelPrivateKey<|||>1<|||>
Servers\nexus_stock_db\SSHtunnelPort<|||>3<|||>3307
Servers\nexus_stock_db\SSL_Active<|||>3<|||>0
Servers\nexus_stock_db\SSL_Key<|||>1<|||>
Servers\nexus_stock_db\SSL_Cert<|||>1<|||>
Servers\nexus_stock_db\SSL_CA<|||>1<|||>
Servers\nexus_stock_db\SSL_Cipher<|||>1<|||>
Servers\nexus_stock_db\SSL_Verification<|||>3<|||>2
Servers\nexus_stock_db\IgnoreDatabasePattern<|||>1<|||>^pg_temp_\d
Servers\nexus_stock_db\LogFileDdl<|||>3<|||>0
Servers\nexus_stock_db\LogFileDml<|||>3<|||>0
Servers\nexus_stock_db\LogFilePath<|||>1<|||>C:\Users\smrj1.DESKTOP-Q4QDIE1\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\nexus_stock_db\ServerVersionFull<|||>1<|||>PostgreSQL 18.0 on x86_64-windows, compiled by msvc-19.44.35215, 64-bit
Servers\nexus_stock_db\ConnectCount<|||>3<|||>5
Servers\nexus_stock_db\ServerVersion<|||>3<|||>180000
Servers\nexus_stock_db\LastConnect<|||>1<|||>2026-05-14 10:10:20
Servers\nexus_stock_db\lastUsedDB<|||>1<|||>public
Servers\nexus_stock_db\FavoriteObjects<|||>1<|||>
Servers\nexus_stock_db\QueryHistory\1<|||>1<|||>2026-05-12 12:37:02||63|-- Creamos las tablas para el sistema de gestión<{{{><}}}>CREATE TABLE categorias (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    nombre VARCHAR(100) NOT NULL,<{{{><}}}>    descripcion TEXT<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE productos (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    codigo_barras VARCHAR(50) UNIQUE,<{{{><}}}>    nombre VARCHAR(150) NOT NULL,<{{{><}}}>    precio_compra NUMERIC(10,2) NOT NULL,<{{{><}}}>    precio_venta NUMERIC(10,2) NOT NULL,<{{{><}}}>    stock INT NOT NULL DEFAULT 0,<{{{><}}}>    categoria_id INT REFERENCES categorias(id)<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE usuarios (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    nombre VARCHAR(100) NOT NULL,<{{{><}}}>    email VARCHAR(150) UNIQUE NOT NULL,<{{{><}}}>    password_hash TEXT NOT NULL,<{{{><}}}>    rol VARCHAR(20) DEFAULT 'vendedor'<{{{><}}}>);
Servers\nexus_stock_db\QueryHistory\2<|||>1<|||>2026-05-12 13:41:49||15|-- 1. Nos aseguramos de estar en el esquema correcto<{{{><}}}>SET search_path TO public;<{{{><}}}><{{{><}}}>-- 2. Borramos si existen (para limpiar errores previos)<{{{><}}}>DROP TABLE IF EXISTS productos;<{{{><}}}>DROP TABLE IF EXISTS categorias;<{{{><}}}><{{{><}}}>-- 3. Creamos la tabla de nuevo en PUBLIC<{{{><}}}>CREATE TABLE categorias (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    nombre VARCHAR(100) NOT NULL,<{{{><}}}>    descripcion TEXT<{{{><}}}>);
Servers\nexus_stock_db\QueryHistory\3<|||>1<|||>2026-05-13 09:30:29||32|CREATE TABLE IF NOT EXISTS public.categorias (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    nombre VARCHAR(100) NOT NULL,<{{{><}}}>    descripcion TEXT<{{{><}}}>);
Servers\nexus_stock_db\QueryHistory\4<|||>1<|||>2026-05-13 09:45:26||0|CREATE TABLE public.productos (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    nombre VARCHAR(100) NOT NULL,<{{{><}}}>    stock INT DEFAULT 0,<{{{><}}}>    precio DECIMAL(10, 2),<{{{><}}}>    categoria_id INT,<{{{><}}}>    CONSTRAINT fk_categoria <{{{><}}}>        FOREIGN KEY(categoria_id) <{{{><}}}>        REFERENCES public.categorias(id) <{{{><}}}>        ON DELETE SET NULL<{{{><}}}>); 
Servers\nexus_stock_db\QueryHistory\5<|||>1<|||>2026-05-13 10:52:23||16|CREATE TABLE public.usuarios (<{{{><}}}>    id SERIAL PRIMARY KEY,<{{{><}}}>    usuario VARCHAR(50) UNIQUE NOT NULL,<{{{><}}}>    password TEXT NOT NULL<{{{><}}}>);<{{{><}}}><{{{><}}}>-- Insertamos tu usuario con una contraseña simple por ahora (puedes cambiarla después)<{{{><}}}>INSERT INTO public.usuarios (usuario, password) <{{{><}}}>VALUES ('admin', '123456');
Servers\reniec_asistencia\SessionCreated<|||>1<|||>2026-05-18 00:18:50
Servers\reniec_asistencia\Host<|||>1<|||>127.0.0.1
Servers\reniec_asistencia\WindowsAuth<|||>3<|||>0
Servers\reniec_asistencia\CleartextPluginEnabled<|||>3<|||>0
Servers\reniec_asistencia\User<|||>1<|||>postgres
Servers\reniec_asistencia\Password<|||>1<|||>77767A7B6E796C7A7
Servers\reniec_asistencia\LoginPrompt<|||>3<|||>0
Servers\reniec_asistencia\Port<|||>1<|||>5432
Servers\reniec_asistencia\NetType<|||>3<|||>8
Servers\reniec_asistencia\Compressed<|||>3<|||>0
Servers\reniec_asistencia\LocalTimeZone<|||>3<|||>0
Servers\reniec_asistencia\QueryTimeout<|||>3<|||>30
Servers\reniec_asistencia\KeepAlive<|||>3<|||>20
Servers\reniec_asistencia\FullTableStatus<|||>3<|||>1
Servers\reniec_asistencia\Databases<|||>1<|||>reniec_asistencia
Servers\reniec_asistencia\Library<|||>1<|||>libpq-15.dll
Servers\reniec_asistencia\Comment<|||>1<|||>
Servers\reniec_asistencia\StartupScriptFilename<|||>1<|||>
Servers\reniec_asistencia\TreeBackground<|||>3<|||>536870911
Servers\reniec_asistencia\SSHtunnelActive<|||>3<|||>0
Servers\reniec_asistencia\SshExecutable<|||>1<|||>plink.exe
Servers\reniec_asistencia\SSHtunnelHost<|||>1<|||>
Servers\reniec_asistencia\SSHtunnelHostPort<|||>3<|||>22
Servers\reniec_asistencia\SSHtunnelUser<|||>1<|||>
Servers\reniec_asistencia\SSHtunnelPassword<|||>1<|||>9
Servers\reniec_asistencia\SSHtunnelTimeout<|||>3<|||>4
Servers\reniec_asistencia\SSHtunnelPrivateKey<|||>1<|||>
Servers\reniec_asistencia\SSHtunnelPort<|||>3<|||>3307
Servers\reniec_asistencia\SSL_Active<|||>3<|||>0
Servers\reniec_asistencia\SSL_Key<|||>1<|||>
Servers\reniec_asistencia\SSL_Cert<|||>1<|||>
Servers\reniec_asistencia\SSL_CA<|||>1<|||>
Servers\reniec_asistencia\SSL_Cipher<|||>1<|||>
Servers\reniec_asistencia\SSL_Verification<|||>3<|||>2
Servers\reniec_asistencia\IgnoreDatabasePattern<|||>1<|||>^pg_temp_\d
Servers\reniec_asistencia\LogFileDdl<|||>3<|||>0
Servers\reniec_asistencia\LogFileDml<|||>3<|||>0
Servers\reniec_asistencia\LogFilePath<|||>1<|||>C:\Users\smrj1.DESKTOP-Q4QDIE1\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\reniec_asistencia\ServerVersionFull<|||>1<|||>PostgreSQL 18.0 on x86_64-windows, compiled by msvc-19.44.35215, 64-bit
Servers\reniec_asistencia\ConnectCount<|||>3<|||>33
Servers\reniec_asistencia\ServerVersion<|||>3<|||>180000
Servers\reniec_asistencia\LastConnect<|||>1<|||>2026-06-04 21:00:39
Servers\reniec_asistencia\lastUsedDB<|||>1<|||>
Servers\reniec_asistencia\RefusedCount<|||>3<|||>2
